package cn.edu.bupt.goods.dao;

public class CategorySecondDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_second.id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_second.name
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_second.category_id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_second.id
     *
     * @return the value of category_second.id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_second.id
     *
     * @param id the value for category_second.id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_second.name
     *
     * @return the value of category_second.name
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_second.name
     *
     * @param name the value for category_second.name
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_second.category_id
     *
     * @return the value of category_second.category_id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_second.category_id
     *
     * @param categoryId the value for category_second.category_id
     *
     * @mbg.generated Sun Nov 15 17:34:50 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}