package cn.edu.bupt.goods.dao;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategorySecondDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    int insert(CategorySecondDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    int insertSelective(CategorySecondDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    CategorySecondDo selectByPrimaryKey(@Param("id") Integer id, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    int updateByPrimaryKeySelective(CategorySecondDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_second
     *
     * @mbg.generated Sun Nov 15 17:01:54 CST 2020
     */
    int updateByPrimaryKey(CategorySecondDo record);

    List<CategorySecondDo> selectByCategoryId(int categoryId);
}