package cn.edu.bupt.goods.dao;

import cn.edu.bupt.goods.dao.CategoryDo;

import java.util.List;

public interface CategoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    int insert(CategoryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    int insertSelective(CategoryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    CategoryDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 15 21:05:39 CST 2020
     */
    int updateByPrimaryKey(CategoryDo record);

    List<CategoryDo> selectAll();
}