package cn.edu.bupt.goods.dao;

import cn.edu.bupt.goods.dao.GoodsDo;

import java.util.List;
import java.util.Map;

public interface GoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    int insert(GoodsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    int insertSelective(GoodsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    GoodsDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Nov 15 04:34:37 CST 2020
     */
    int updateByPrimaryKey(GoodsDo record);

    List<GoodsDo> selectByCategoryIdPage(Map<String, Integer> params);

    List<GoodsDo> selectByCategorySecondIdPage(Map<String, Integer> params);

    List<GoodsDo> selectAll();
}