package cn.edu.bupt.goods.dao;

public class GoodsDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.rest
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private Integer rest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_category_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private Integer goodCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category_second_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private Integer categorySecondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.owner_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    private String ownerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img
     *
     * @return the value of goods.img
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img
     *
     * @param img the value for goods.img
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.rest
     *
     * @return the value of goods.rest
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public Integer getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.rest
     *
     * @param rest the value for goods.rest
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setRest(Integer rest) {
        this.rest = rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_category_id
     *
     * @return the value of goods.good_category_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public Integer getGoodCategoryId() {
        return goodCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_category_id
     *
     * @param goodCategoryId the value for goods.good_category_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setGoodCategoryId(Integer goodCategoryId) {
        this.goodCategoryId = goodCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category_second_id
     *
     * @return the value of goods.category_second_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public Integer getCategorySecondId() {
        return categorySecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category_second_id
     *
     * @param categorySecondId the value for goods.category_second_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setCategorySecondId(Integer categorySecondId) {
        this.categorySecondId = categorySecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.owner_id
     *
     * @return the value of goods.owner_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.owner_id
     *
     * @param ownerId the value for goods.owner_id
     *
     * @mbg.generated Sun Nov 15 16:05:35 CST 2020
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }
}